### ISSUE TITLE
feature:remove this fr

### ISSUE THREAD

**Issue by nightwank** [Somali-Devs/Kematian-Stealer#183]
### What Feature?

when i open it a txt file appears, where u can read the code, and u can also read things like steam session stealer, epic games session stealer, defender bypass, whatsapp session stealer

### Add Screenshots (If Applicable)

![image_2024-05-01_155221223](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/168483340/10db5d51-2cc4-46ea-b37a-164dcf075a75)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> when i open it a txt file appears, where u can read the code, and u can also read things like steam session stealer, epic games session stealer, defender bypass, whatsapp session stealer
> 
> ### Add Screenshots (If Applicable)
> 
> 
> 
> ![image_2024-05-01_155221223](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/168483340/10db5d51-2cc4-46ea-b37a-164dcf075a75)
> 
> 
> 
> 
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/issues)
> - [ ] I want to work on this feature

So what's the issue???

**Comment by nightwank** [comment]
it tells them that they got grabbed basically

**Comment by nightwank** [comment]
when they open the grabber it also opens this 
![image](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/168483340/66e7504d-1872-432f-a001-e123b3faf8fa)

**Comment by KDot227** [comment]
> when they open the grabber it also opens this ![image](https://private-user-images.githubusercontent.com/168483340/327199441-66e7504d-1872-432f-a001-e123b3faf8fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjEwOTcsIm5iZiI6MTcxNTAyMDc5NywicGF0aCI6Ii8xNjg0ODMzNDAvMzI3MTk5NDQxLTY2ZTc1MDRkLTE4NzItNDMyZi1hMDAxLWUxMjNiM2ZhZjhmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxODM5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGY3MjQ1YTgwMDk3ODI2MWUzNDgyMTI5MTEwNWM3NmZiMWFkNDlkZThjYTJjZjljYzM2MDY1Mjc4Mjc4NjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2PC1W8K7N91sy05IdtZE6SSs1mOPTRip03x-osH8C9w)

Is that a screenshot that it opens or does it just open that in notepad without executing?

**Comment by KDot227** [comment]
@nightwank ?

**Comment by nightwank** [comment]
> @nightwank ?

when they run the stealer it opens that notepad

**Comment by KDot227** [comment]
> > @nightwank ?
> 
> when they run the stealer it opens that notepad

that is probably because you changed how powershell files are ran on your pc. Can you add me on discord so I can try and help you through this? My user is kdot_227
