### ISSUE TITLE
feature: Discord to ask questions

### ISSUE THREAD

**Issue by Moomoomilkers** [Somali-Devs/Kematian-Stealer#247]
### What Feature?

Hey - I wanted to ask which specific piece or pieces of code are closing chrome tabs when the program is ran. If it's complicated, can I get your discord to discuss it further? The github bot link isn't working.

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> Hey - I wanted to ask which specific piece or pieces of code are closing chrome tabs when the program is ran. If it's complicated, can I get your discord to discuss it further? The github bot link isn't working.
> 
> ### Add Screenshots (If Applicable)
> 
> _No response_
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> - [ ] I want to work on this feature

sped.lol/discord
