### ISSUE TITLE
feature:Add fake error as a config option directly from the builder

### ISSUE THREAD

**Issue by grumach** [Somali-Devs/Kematian-Stealer#251]
### What Feature?

Unless I cannot read at all in the builder there is no option to turn on fake error config that exists and does work

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Somali-Devs/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> Unless I cannot read at all in the builder there is no option to turn on fake error config that exists and does work
> 
> ### Add Screenshots (If Applicable)
> 
> _No response_
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/Somali-Devs/Kematian-Stealer/issues)
> - [ ] I want to work on this feature

Currently you can only change the setting if you change it within the powershell. In V3 the builder will have an option to change it don't worry.

**Comment by KDot227** [comment]
V3 NOW COMPLETELY SUPPORTS
