### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by xxopenxx** [Somali-Devs/Kematian-Stealer#255]
### What Feature?

can you send new discord?

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Somali-Devs/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> can you send new discord?
> 
> ### Add Screenshots (If Applicable)
> 
> _No response_
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/Somali-Devs/Kematian-Stealer/issues)
> - [ ] I want to work on this feature

Sped.lol/discord

**Comment by xxopenxx** [comment]
pls give new

**Comment by KDot227** [comment]
> pls give new

https://t.me/+RHUnNVumwmlmM2Fh
