### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by 43a1723** [Somali-Devs/Kematian-Stealer#256]
### What Did You Expect To Happen?

V3 = V2

### What Happened?

I can't use Kematian-Stealer V3

### Add Screenshots

![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/170785112/99a30604-37c5-476f-998e-6d277d2eceb6)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Somali-Devs/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by 43a1723** [comment]
sorry :)

**Comment by KDot227** [comment]
> sorry :)
> 
> 

What???

**Comment by KDot227** [comment]
The autorun.ps1 isn't even being used anymore in V3 thank you for reminding me to delete it.
