### ISSUE TITLE
Bug:  cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by ZaiTheDragon** [Somali-Devs/Kematian-Stealer#257]
### What Did You Expect To Happen?

I expected the batch file to run and do the specified 'builder' thing.

### What Happened?

I got the error : # runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

error building application: exit status 1
'dist\Builder.exe' is not recognized as an internal or external command,
operable program or batch file.
9009

### Add Screenshots

![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/173625590/1d18d90f-2b03-4c1f-9726-aec43b437352)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Somali-Devs/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by ZaiTheDragon** [comment]
also add me on discord if needed (ask for my name)

**Comment by KDot227** [comment]
> also add me on discord if needed (ask for my name)

Read everything that to builder says and the error. If you want to build from source you need golang and the mingw toolchain.
