### ISSUE TITLE
Bug: Anti-vm is enabled even if the checkbox is not ticked

### ISSUE THREAD

**Issue by xxopenxx** [Somali-Devs/Kematian-Stealer#262]
### What Did You Expect To Happen?

expecting to get obfuscated file with anti-vm disabled

### What Happened?

I'm not sure if it's a bug, anti-vm is working fine BUT without option "obfuscate". When I want to combine those 2 options, to have obfuscated file but with anti-vm disabled, it's not working beacuse somaliobf is doing anti-vm automatically. (I guess)

Let me know, great work bro :)

### Add Screenshots

no screenshots

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by KDot227** [comment]
> ### What Did You Expect To Happen?
> 
> expecting to get obfuscated file with anti-vm disabled
> ### What Happened?
> 
> I'm not sure if it's a bug, anti-vm is working fine BUT without option "obfuscate". When I want to combine those 2 options, to have obfuscated file but with anti-vm disabled, it's not working beacuse somaliobf is doing anti-vm automatically. (I guess)
> 
> Let me know, great work bro :)
> ### Add Screenshots
> 
> no screenshots
> ### Check the following before submitting (If Applicable)
> 
>     * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> 
>     * [x]  I have attempted to resolve my problem by myself

Somalifuscator naturally has anti vm.
