### ISSUE TITLE
Bug: Making FUD

### ISSUE THREAD

**Issue by alkabane** [Somali-Devs/Kematian-Stealer#265]
### What Did You Expect To Happen?

detected :(

### What Happened?

av detected

### Add Screenshots

:(

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by KDot227** [comment]
> ### What Did You Expect To Happen?
> 
> detected :(
> ### What Happened?
> 
> av detected
> ### Add Screenshots
> 
> :(
> ### Check the following before submitting (If Applicable)
> 
>     * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> 
>     * [x]  I have attempted to resolve my problem by myself

bro what? 💀
