### ISSUE TITLE
Bugkdot.ps1 permission denied

### ISSUE THREAD

**Issue by kzb399** [Somali-Devs/Kematian-Stealer#269]
### What Did You Expect To Happen?

in cmdprompt i get kdot.ps1 permission denied

### What Happened?

 n

### Add Screenshots

![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/144407241/e890557e-3739-432c-85e1-5305bdbe4cb4)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [X] I have attempted to resolve my problem by myself

**Comment by KDot227** [comment]
Restart your pc

**Comment by kzb399** [comment]
i tried that, nothing changed

**Comment by KDot227** [comment]
> i tried that, nothing changed

Try running with admin. If that doesn't work then it means the kdot.ps1 file is currently running and you can kill it with "taskill /f /im powershell.exe"

**Comment by kzb399** [comment]
ok it says payload built succesfully now. But where do I find what it built?

**Comment by kzb399** [comment]
I also keep getting this error: 
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/144407241/78de85e5-cd3a-4263-ac99-41c3933a0f9d)

**Comment by KDot227** [comment]
> I also keep getting this error: 
> 
> ![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/144407241/78de85e5-cd3a-4263-ac99-41c3933a0f9d)
> 
> 
> 
> 

That's fine just ignore it there is prolly some other application fighting kematian lol

**Comment by KDot227** [comment]
> ok it says payload built succesfully now. But where do I find what it built?

Same directory as main.exe or source.

**Comment by kzb399** [comment]
I dont see it in my downloads folder or C drive where main.exe is. am I just being retarded? lol

**Comment by KDot227** [comment]
> I dont see it in my downloads folder or C drive where main.exe is. am I just being retarded? lol
> 
> 

Look harder or close and reopen your file explorer.

**Comment by kzb399** [comment]
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/144407241/482861da-ca6a-4167-9ee0-20539d2b84d9)

**Comment by kzb399** [comment]
its just not there for mee, i searched everywhere. I tried batch file and still nothing

**Comment by KDot227** [comment]
> its just not there for mee, i searched everywhere. I tried batch file and still nothing
> 
> 

It's the kdot.ps1 file u built as powershell not bat 🤦‍♂️
