### ISSUE TITLE
Suggestion: Stop being idiots

### ISSUE THREAD

**Issue by catn1pdeal3r** [Somali-Devs/Kematian-Stealer#270]
### What Feature?

Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked. 

Below is a list of active servers running your shitty stealer:
https://64.52.80.191:8080/
https://82.117.255.71:8080/

I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.

### Check the following before submitting (If Applicable)

- [x] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked. 
> 
> 
> 
> Below is a list of active servers running your shitty stealer:
> 
> https://64.52.80.191:8080/
> 
> https://82.117.255.71:8080/
> 
> 
> 
> I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> 
> ### Add Screenshots (If Applicable)
> 
> _No response_
> 
> ### Check the following before submitting (If Applicable)
> 
> - [x] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> - [ ] I want to work on this feature

1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.

2.) no shit there is no auth it's literally a web panel that's locally hosted.

3.) I think whoever made the UI would feel very hurt you said that.

4.) The code structure is perfectly fine lmfao.

5.) Neither of those ips have anything to do with me or any of the other contributors.

**Comment by catn1pdeal3r** [comment]
> > ### What Feature?
> > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > Below is a list of active servers running your shitty stealer:
> > https://64.52.80.191:8080/
> > https://82.117.255.71:8080/
> > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > ### Add Screenshots (If Applicable)
> > _No response_
> > ### Check the following before submitting (If Applicable)
> > 
> > * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > * [ ]  I want to work on this feature
> 
> 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> 
> 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> 
> 3.) I think whoever made the UI would feel very hurt you said that.
> 
> 4.) The code structure is perfectly fine lmfao.
> 
> 5.) Neither of those ips have anything to do with me or any of the other contributors.

I really doubt you aren't using this to harm others and for a fact I know you're using it at this moment because why would this be online? https://sped.lol/get_members Also I suggest you learn how to make redirects because an html file with just a discord link isn't doing it.

**Comment by catn1pdeal3r** [comment]
> > ### What Feature?
> > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > Below is a list of active servers running your shitty stealer:
> > https://64.52.80.191:8080/
> > https://82.117.255.71:8080/
> > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > ### Add Screenshots (If Applicable)
> > _No response_
> > ### Check the following before submitting (If Applicable)
> > 
> > * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > * [ ]  I want to work on this feature
> 
> 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> 
> 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> 
> 3.) I think whoever made the UI would feel very hurt you said that.
> 
> 4.) The code structure is perfectly fine lmfao.
> 
> 5.) Neither of those ips have anything to do with me or any of the other contributors.

Oh and I know those aren't your ips I never said they were, what I said is active servers running it never mentioned you in that.

**Comment by KDot227** [comment]
> > > ### What Feature?
> > > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > > Below is a list of active servers running your shitty stealer:
> > > https://64.52.80.191:8080/
> > > https://82.117.255.71:8080/
> > > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > > ### Add Screenshots (If Applicable)
> > > _No response_
> > > ### Check the following before submitting (If Applicable)
> > > 
> > > * [x]   I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > > * [ ]   I want to work on this feature
> > 
> > 
> > 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> > 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> > 3.) I think whoever made the UI would feel very hurt you said that.
> > 4.) The code structure is perfectly fine lmfao.
> > 5.) Neither of those ips have anything to do with me or any of the other contributors.
> 
> I really doubt you aren't using this to harm others and for a fact I know you're using it at this moment because why would this be online? https://sped.lol/get_members Also I suggest you learn how to make redirects because an html file with just a discord link isn't doing it.

your wrong... your thinking of this

![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/110929758/ae60404c-4787-4c26-8937-c2b2f27d7009)

also the discord doesn't even work anymore I just haven't removed it yet lmfao.

**Comment by KDot227** [comment]
and the "/get_messages" call is for the chat in the ui 🤦‍♂️ so before you start acting like a hero use your brain first.

**Comment by catn1pdeal3r** [comment]
No shit it's for the chat in the UI. Why would it even be on the webserver because I really doubt your using it for good reasons. Oh and also why did you clear them?

**Comment by catn1pdeal3r** [comment]
> > > > ### What Feature?
> > > > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > > > Below is a list of active servers running your shitty stealer:
> > > > https://64.52.80.191:8080/
> > > > https://82.117.255.71:8080/
> > > > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > > > ### Add Screenshots (If Applicable)
> > > > _No response_
> > > > ### Check the following before submitting (If Applicable)
> > > > 
> > > > * [x]    I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > > > * [ ]    I want to work on this feature
> > > 
> > > 
> > > 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> > > 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> > > 3.) I think whoever made the UI would feel very hurt you said that.
> > > 4.) The code structure is perfectly fine lmfao.
> > > 5.) Neither of those ips have anything to do with me or any of the other contributors.
> > 
> > 
> > I really doubt you aren't using this to harm others and for a fact I know you're using it at this moment because why would this be online? https://sped.lol/get_members Also I suggest you learn how to make redirects because an html file with just a discord link isn't doing it.
> 
> your wrong... your thinking of this
> 
> ![image](https://private-user-images.githubusercontent.com/110929758/345293536-ae60404c-4787-4c26-8937-c2b2f27d7009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODU3MDUsIm5iZiI6MTcxOTk4NTQwNSwicGF0aCI6Ii8xMTA5Mjk3NTgvMzQ1MjkzNTM2LWFlNjA0MDRjLTQ3ODctNGMyNi04OTM3LWMyYjJmMjdkNzAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNTQzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjBkNGFmNzBiYTFmZGJkNmQ0ZWJlNzA1ZGU0NWEyYzM2YTdmYWViNWUyY2I2OTg1ZmY4MzcyNDU1ZGUyZGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EVZu4mZQrB_79DH0_Ik7iY6KBVN1chHlMv0_GfA8whA)
> 
> also the discord doesn't even work anymore I just haven't removed it yet lmfao.

Please use correct grammar it's "you're"

**Comment by KDot227** [comment]
> No shit it's for the chat in the UI. Why would it even be on the webserver because I really doubt your using it for good reasons. Oh and also why did you clear them?

1.) The chat is literally just for fun quit being a weirdo.
2.) I don't clear them. They don't have a db at all. Anytime the server updates or has downtime and has to restart (the hosting service is render.com) the messages clear. They also only hold up to 50 messages at one time so the server doesn't use too much memory.

**Comment by KDot227** [comment]
> > > > > ### What Feature?
> > > > > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > > > > Below is a list of active servers running your shitty stealer:
> > > > > https://64.52.80.191:8080/
> > > > > https://82.117.255.71:8080/
> > > > > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > > > > ### Add Screenshots (If Applicable)
> > > > > _No response_
> > > > > ### Check the following before submitting (If Applicable)
> > > > > 
> > > > > * [x]     I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > > > > * [ ]     I want to work on this feature
> > > > 
> > > > 
> > > > 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> > > > 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> > > > 3.) I think whoever made the UI would feel very hurt you said that.
> > > > 4.) The code structure is perfectly fine lmfao.
> > > > 5.) Neither of those ips have anything to do with me or any of the other contributors.
> > > 
> > > 
> > > I really doubt you aren't using this to harm others and for a fact I know you're using it at this moment because why would this be online? https://sped.lol/get_members Also I suggest you learn how to make redirects because an html file with just a discord link isn't doing it.
> > 
> > 
> > your wrong... your thinking of this
> > ![image](https://private-user-images.githubusercontent.com/110929758/345293536-ae60404c-4787-4c26-8937-c2b2f27d7009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODU3MDUsIm5iZiI6MTcxOTk4NTQwNSwicGF0aCI6Ii8xMTA5Mjk3NTgvMzQ1MjkzNTM2LWFlNjA0MDRjLTQ3ODctNGMyNi04OTM3LWMyYjJmMjdkNzAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNTQzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjBkNGFmNzBiYTFmZGJkNmQ0ZWJlNzA1ZGU0NWEyYzM2YTdmYWViNWUyY2I2OTg1ZmY4MzcyNDU1ZGUyZGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EVZu4mZQrB_79DH0_Ik7iY6KBVN1chHlMv0_GfA8whA)
> > also the discord doesn't even work anymore I just haven't removed it yet lmfao.
> 
> Please use correct grammar it's "you're"

Grammar police!!!!

**Comment by catn1pdeal3r** [comment]
> > > > > > ### What Feature?
> > > > > > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > > > > > Below is a list of active servers running your shitty stealer:
> > > > > > https://64.52.80.191:8080/
> > > > > > https://82.117.255.71:8080/
> > > > > > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > > > > > ### Add Screenshots (If Applicable)
> > > > > > _No response_
> > > > > > ### Check the following before submitting (If Applicable)
> > > > > > 
> > > > > > * [x]      I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > > > > > * [ ]      I want to work on this feature
> > > > > 
> > > > > 
> > > > > 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> > > > > 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> > > > > 3.) I think whoever made the UI would feel very hurt you said that.
> > > > > 4.) The code structure is perfectly fine lmfao.
> > > > > 5.) Neither of those ips have anything to do with me or any of the other contributors.
> > > > 
> > > > 
> > > > I really doubt you aren't using this to harm others and for a fact I know you're using it at this moment because why would this be online? https://sped.lol/get_members Also I suggest you learn how to make redirects because an html file with just a discord link isn't doing it.
> > > 
> > > 
> > > your wrong... your thinking of this
> > > ![image](https://private-user-images.githubusercontent.com/110929758/345293536-ae60404c-4787-4c26-8937-c2b2f27d7009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODU3MDUsIm5iZiI6MTcxOTk4NTQwNSwicGF0aCI6Ii8xMTA5Mjk3NTgvMzQ1MjkzNTM2LWFlNjA0MDRjLTQ3ODctNGMyNi04OTM3LWMyYjJmMjdkNzAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNTQzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjBkNGFmNzBiYTFmZGJkNmQ0ZWJlNzA1ZGU0NWEyYzM2YTdmYWViNWUyY2I2OTg1ZmY4MzcyNDU1ZGUyZGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EVZu4mZQrB_79DH0_Ik7iY6KBVN1chHlMv0_GfA8whA)
> > > also the discord doesn't even work anymore I just haven't removed it yet lmfao.
> > 
> > 
> > Please use correct grammar it's "you're"
> 
> Grammar police!!!!

Yes, anyway I hope I can trust your word that you are not using it. I have a suggestion to make sure the stealer can't be used for harmful intentions so if you can put precautions in the code to make sure it's being hosted on a private network(we know the people using this don't know how to remove them).

**Comment by KDot227** [comment]
> > > > > > > ### What Feature?
> > > > > > > Ok so I would like to start by saying you are horrible people for even creating this but making it open source makes it so much worse, and if I may add it's a pile of garbage. No authentication for the webserver, ui is just horrendous and the whole code structure is fucked.
> > > > > > > Below is a list of active servers running your shitty stealer:
> > > > > > > https://64.52.80.191:8080/
> > > > > > > https://82.117.255.71:8080/
> > > > > > > I hope you are happy with the decision you chose of causing harm to others, I wish you a horrible day.
> > > > > > > ### Add Screenshots (If Applicable)
> > > > > > > _No response_
> > > > > > > ### Check the following before submitting (If Applicable)
> > > > > > > 
> > > > > > > * [x]       I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > > > > > > * [ ]       I want to work on this feature
> > > > > > 
> > > > > > 
> > > > > > 1.) it's meant for red teamer's. If some random kid uses it that isn't my fault.
> > > > > > 2.) no shit there is no auth it's literally a web panel that's locally hosted.
> > > > > > 3.) I think whoever made the UI would feel very hurt you said that.
> > > > > > 4.) The code structure is perfectly fine lmfao.
> > > > > > 5.) Neither of those ips have anything to do with me or any of the other contributors.
> > > > > 
> > > > > 
> > > > > I really doubt you aren't using this to harm others and for a fact I know you're using it at this moment because why would this be online? https://sped.lol/get_members Also I suggest you learn how to make redirects because an html file with just a discord link isn't doing it.
> > > > 
> > > > 
> > > > your wrong... your thinking of this
> > > > ![image](https://private-user-images.githubusercontent.com/110929758/345293536-ae60404c-4787-4c26-8937-c2b2f27d7009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODU3MDUsIm5iZiI6MTcxOTk4NTQwNSwicGF0aCI6Ii8xMTA5Mjk3NTgvMzQ1MjkzNTM2LWFlNjA0MDRjLTQ3ODctNGMyNi04OTM3LWMyYjJmMjdkNzAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNTQzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjBkNGFmNzBiYTFmZGJkNmQ0ZWJlNzA1ZGU0NWEyYzM2YTdmYWViNWUyY2I2OTg1ZmY4MzcyNDU1ZGUyZGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EVZu4mZQrB_79DH0_Ik7iY6KBVN1chHlMv0_GfA8whA)
> > > > also the discord doesn't even work anymore I just haven't removed it yet lmfao.
> > > 
> > > 
> > > Please use correct grammar it's "you're"
> > 
> > 
> > Grammar police!!!!
> 
> Yes, anyway I hope I can trust your word that you are not using it. I have a suggestion to make sure the stealer can't be used for harmful intentions so if you can put precautions in the code to make sure it's being hosted on a private network(we know the people using this don't know how to remove them).

1.) in a red team environment you would have to use things like port forwarding and you wouldn't be on their private network. 

2.) There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no.

**Comment by catn1pdeal3r** [comment]
Well are you selling illegal guns?

**Comment by KDot227** [comment]
> Well are you selling illegal guns?

it's a metaphor 🤦‍♂️

**Comment by catn1pdeal3r** [comment]
I know but I'm asking anyway

**Comment by KDot227** [comment]
> I know but I'm asking anyway

no bruh like what

**Comment by catn1pdeal3r** [comment]
I have one more thing, why is it called a stealer? If its meant for red teams or similar situations why isn't it named something that suits it more? I would think having called it something other than a stealer would make it less likely for others to use it for harm. I do not blame you for harm others have cause this is an actual question I'm curious about.

**Comment by KDot227** [comment]
> I have one more thing, why is it called a stealer? If its meant for red teams or similar situations why isn't it named something that suits it more? I would think having called it something other than a stealer would make it less likely for others to use it for harm. I do not blame you for harm others have cause this is an actual question I'm curious about.

Because it's job is to steal...

**Comment by catn1pdeal3r** [comment]
Ok so it's meant to harm

**Comment by KDot227** [comment]
> Ok so it's meant to harm

yes that's the point of red team tools 🤦‍♂️

**Comment by catn1pdeal3r** [comment]
For a red team environment I would think just getting the software on the victims device would be enough to prove the issues they have. What's the need for it to steal information.

**Comment by KDot227** [comment]
> For a red team environment I would think just getting the software on the victims device would be enough to prove the issues they have. What's the need for it to steal information.

for example AV testing or seeing how it would act on their network. There are many use cases.

**Comment by catn1pdeal3r** [comment]
Ah so a steam, battlenet, and minecraft stealer are needed to test the security in a work environment?

**Comment by KDot227** [comment]
> Ah so a steam, battlenet, and minecraft stealer are needed to test the security in a work environment?

if someone tells me to add a feature I add it 🤷‍♂️

**Comment by catn1pdeal3r** [comment]
It's kind of obvious what they are using it for if they asked for a minecraft stealer

**Comment by EvilBytecode** [comment]
someone getting clowned 💀 gj @catn1pdeal3r

**Comment by KDot227** [comment]
> someone getting clowned 💀 gj @catn1pdeal3r

How slow can you humanly be. He's talking about the same thing that you do too. If you even read any of our conversations you would realize that, but in the end he wouldn't be able to read your code 🤷‍♂️.

**Comment by EvilBytecode** [comment]
"No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off

**Comment by KDot227** [comment]
> "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off

"Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.

**Comment by catn1pdeal3r** [comment]
> > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> 
> "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.

I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!

**Comment by KDot227** [comment]
> > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> > 
> > 
> > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> 
> I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!

"There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."

**Comment by catn1pdeal3r** [comment]
> > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> > > 
> > > 
> > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> > 
> > 
> > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> 
> "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."



> > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> > > 
> > > 
> > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> > 
> > 
> > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> 
> "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."

Well are you selling illegal guns?

**Comment by KDot227** [comment]
> > > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> 
> > > > 
> 
> > > > 
> 
> > > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> 
> > > 
> 
> > > 
> 
> > > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> 
> > 
> 
> > "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."
> 
> 
> 
> 
> 
> 
> 
> > > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> 
> > > > 
> 
> > > > 
> 
> > > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> 
> > > 
> 
> > > 
> 
> > > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> 
> > 
> 
> > "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."
> 
> 
> 
> Well are you selling illegal guns?

Do you understand what a metaphor is?

**Comment by catn1pdeal3r** [comment]
> > > > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> > 
> > 
> > > 
> > 
> > 
> > > "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."
> > 
> > 
> > > > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> > 
> > 
> > > 
> > 
> > 
> > > "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."
> > 
> > 
> > Well are you selling illegal guns?
> 
> Do you understand what a metaphor is?

Well of course but are you selling illegal guns?

**Comment by KDot227** [comment]
> > > > > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."
> 
> > > 
> 
> > > 
> 
> > > > > > > "No srp = bad coder" 🤣🤣 bro, Ive got told that only in job y Gotta follow it, is my github project making rn some kind of income?? Nope😂😂 so hop off
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > "Hop off" you're literally going into my GitHub issues like a 7 year old to argue 💀💀💀. Not only do you not understand the fundamentals of making good quality code you try to make excuses on why you don't do it, and then when someone else has it, you try and say they have "ChatGPT code". All I can do for you now is pray that you get better.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I thought this was done with but you're the one trying to argue that just because you put "for education purposes only" it's okay to harm people, but nah it's very legal. Have a great day!
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > "There are already messages in the readme saying it's for professional use purposes only. No matter what I do people will still believe I'm in the wrong. If you sell guns for a living and sell one to a normal guy who claims to have no bad intentions (that you know of) then am I the bad guy for giving him the gun if he uses it for murder? no."
> 
> > > 
> 
> > > 
> 
> > > Well are you selling illegal guns?
> 
> > 
> 
> > Do you understand what a metaphor is?
> 
> 
> 
> Well of course but are you selling illegal guns?

No bro u can't understand a metaphor to save your life

**Comment by catn1pdeal3r** [comment]
I definitely can but you are just so fucked out of your mind that you can't understand that I don't give one fuck about your metaphor

**Comment by KDot227** [comment]
> I definitely can but you are just so fucked out of your mind that you can't understand that I don't give one fuck about your metaphor 

Bros a little hangry

**Comment by catn1pdeal3r** [comment]
No I just don't like you
