### ISSUE TITLE
feature: Alot of the people i get have discord open in the screenshot but the discord.json is NULL

### ISSUE THREAD

**Issue by Agonyxxx** [Somali-Devs/Kematian-Stealer#271]
### What Feature?

Discord from browser/idk why it says null although in the screenshot discord is open app or browser.
Discord Injection.
Exodus/Atomic injection.
Crypto Clipper.

### Add Screenshots (If Applicable)

![screenshot](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/4238de94-ed37-44a1-8b65-9f1bb4b4b1bc)
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/18b03719-1d0b-4014-8619-7df0a13d9247)
another one he literally has discord opened but look at the discord.json
![screenshot](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/1defdae4-99ad-4333-80e7-7972a4b47f91)
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/5e1d534e-5fc0-42f1-904f-bba92f0e716c)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> Discord from browser/idk why it says null although in the screenshot discord is open app or browser.
> 
> Discord Injection.
> 
> Exodus/Atomic injection.
> 
> Crypto Clipper.
> 
> ### Add Screenshots (If Applicable)
> 
> ![screenshot](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/4238de94-ed37-44a1-8b65-9f1bb4b4b1bc)
> 
> ![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/18b03719-1d0b-4014-8619-7df0a13d9247)
> 
> another one he literally has discord opened but look at the discord.json
> 
> ![screenshot](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/1defdae4-99ad-4333-80e7-7972a4b47f91)
> 
> ![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/5e1d534e-5fc0-42f1-904f-bba92f0e716c)
> 
> 
> 
> ### Check the following before submitting (If Applicable)
> 
> - [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> - [ ] I want to work on this feature

Is it getting your discord?

**Comment by Agonyxxx** [comment]
what do you mean it gets my discord ? idk i haven't tried it on me

**Comment by Agonyxxx** [comment]
some times it gives discord some times it doesn't like it's 50/50

**Comment by KDot227** [comment]
> some times it gives discord some times it doesn't like it's 50/50

If you were to run it on yourself does it give you the discord or no.

**Comment by Agonyxxx** [comment]
it does

**Comment by KDot227** [comment]
> it does 
> 
> Edit just got a log with discord but idk why in some cases like people having discord open and it says null

If anyone you know who can help me test gets null I can fix it. Otherwise there is nothing I can do.

**Comment by Agonyxxx** [comment]
hmm okay appreciate your time for responding what about the features tho

**Comment by KDot227** [comment]
> hmm okay appreciate your time for responding what about the features tho 

I'm working on injections rn. Crypto clipper is something I don't want to do tbh since it would require the process to be running at all times and I don't want to do that since it's meant to be a stealer.

**Comment by Agonyxxx** [comment]
i tried to add the stealer myself but the code broke for some reason

**Comment by KDot227** [comment]
> i tried to add the clipper  myself but the code broke for some reason

I mean I can always have it work similar to how I plan the injecting on working but it would be very complicated and I doubt it would work that well.

**Comment by Agonyxxx** [comment]
alright thank you Dot

**Comment by Agonyxxx** [comment]
an update idk whats going on but there is no discord being captured after the last 3 builders and passwords are always empty

**Comment by KDot227** [comment]
> an update idk whats going on but there is no discord being captured after the last 3 builders and passwords are always empty 

After the update an hour ago or so???

**Comment by Agonyxxx** [comment]
no since last week

**Comment by Agonyxxx** [comment]
![screenshot](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/87066b57-f1c6-471d-aa5e-fe340adf6fed)
[discord.json](https://github.com/user-attachments/files/16136375/discord.json)

**Comment by Agonyxxx** [comment]
idk whats wrong lol

**Comment by Agonyxxx** [comment]
even in cookies when i import them it doesn't detect discord too

**Comment by KDot227** [comment]
> no since last week 

Give me your discord so you can help me bug test

**Comment by Agonyxxx** [comment]
zzagony_78862

**Comment by Agonyxxx** [comment]
@KDot227 does the cam.ps1 has to do anything with it because i removed the camera capture and reuploaded the ps

**Comment by KDot227** [comment]
> @KDot227 does the cam.ps1 has to do anything with it because i removed the camera capture and reuploaded the ps

I don't think so

**Comment by KDot227** [comment]
I added you

**Comment by Agonyxxx** [comment]
After the Update 
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/3f2c0c8a-a717-4dd6-847b-65c62bd0bf57)
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/afebf121-d6e3-4788-9185-7f1daf8451cb)
no browser no discord.json and he has 2 discords opened lmao

**Comment by Agonyxxx** [comment]
Update same person got Logged again after update everything worked now 
![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/d8c91107-69f9-4910-bb45-c318040cd11f)

**Comment by Agonyxxx** [comment]
didn't get browser edge cookies tho idk where the issue is tbh i'll just wait

**Comment by Agonyxxx** [comment]
Update got a log with blank screenshot and null discord the empty screenshot is new so i thought maybe i had to let u know

**Comment by KDot227** [comment]
> Update got a log with blank screenshot and null discord the empty screenshot is new so i thought maybe i had to let u know 

That's prolly a virus total vm

**Comment by KDot227** [comment]
> Update same person got Logged again after update everything worked now 
> 
> ![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/172048629/d8c91107-69f9-4910-bb45-c318040cd11f)
> 
> 

W

**Comment by KDot227** [comment]
> didn't get browser edge cookies tho idk where the issue is tbh i'll just wait 

I'll test on windows 10 and 11 vm and see if I can reproduce. Does their username have a space in it?

**Comment by KDot227** [comment]
STABLE NOW
