### ISSUE TITLE
feature: Interesting features

### ISSUE THREAD

**Issue by IMWurden** [Somali-Devs/Kematian-Stealer#275]
### What Feature?

Those would be some cool features that you should add to make it the best stealer: credit/debit card stealer, Roblox session stealer, Install file in the victim pc and add more supported browser like Chrome,  Edge, Brave, Opera, OperaGX, OperaNeon, Yandex....

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
- [ ] I want to work on this feature

**Comment by KDot227** [comment]
> ### What Feature?
> 
> 
> 
> Those would be some cool features that you should add to make it the best stealer: credit/debit card stealer, Roblox session stealer, Install file in the victim pc and add more supported browser like Chrome,  Edge, Brave, Opera, OperaGX, OperaNeon, Yandex....
> 
> 
> 
> 
> 
> 
> 
> ### Add Screenshots (If Applicable)
> 
> 
> 
> _No response_
> 
> 
> 
> ### Check the following before submitting (If Applicable)
> 
> 
> 
> - [X] I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> 
> - [ ] I want to work on this feature

Everything you mentioned is already added except executing your own file.

**Comment by IMWurden** [comment]
Is there also the Discord payment method info stealer features?

**Comment by IMWurden** [comment]
> > ### What Feature?
> > Those would be some cool features that you should add to make it the best stealer: credit/debit card stealer, Roblox session stealer, Install file in the victim pc and add more supported browser like Chrome,  Edge, Brave, Opera, OperaGX, OperaNeon, Yandex....
> > ### Add Screenshots (If Applicable)
> > _No response_
> > ### Check the following before submitting (If Applicable)
> > 
> > * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> > * [ ]  I want to work on this feature
> 
> Everything you mentioned is already added except executing your own file.

Is there also the Discord payment method info stealer features?

**Comment by KDot227** [comment]
> > > ### What Feature?
> 
> > > Those would be some cool features that you should add to make it the best stealer: credit/debit card stealer, Roblox session stealer, Install file in the victim pc and add more supported browser like Chrome,  Edge, Brave, Opera, OperaGX, OperaNeon, Yandex....
> 
> > > ### Add Screenshots (If Applicable)
> 
> > > _No response_
> 
> > > ### Check the following before submitting (If Applicable)
> 
> > > 
> 
> > > * [x]  I have checked the existing [issues](https://github.com/ChildrenOfYahweh/Kematian-Stealer/issues)
> 
> > > * [ ]  I want to work on this feature
> 
> > 
> 
> > Everything you mentioned is already added except executing your own file.
> 
> 
> 
> Is there also the Discord payment method info stealer features?

Yes

**Comment by IMWurden** [comment]
> > > > ### What Feature?

uh ok cool, thanks for the support!
