### ISSUE TITLE
which file do i give to someone to get info ex: discord token

### ISSUE THREAD

**Issue by ytexotic14** [Somali-Devs/Kematian-Stealer#277]
hello, i was researching on which file to give victims to get there info ex: discord tokens and when i click build exe when using the powershell token grabber i installed somalifuscator but dont really know what to do with it. ik these are really stupid questions but i dont  know much about code and was wondering if i could get help with these issues ive come accross. thanks!

**Comment by KDot227** [comment]
> hello, i was researching on which file to give victims to get there info ex: discord tokens and when i click build exe when using the powershell token grabber i installed somalifuscator but dont really know what to do with it. ik these are really stupid questions but i dont know much about code and was wondering if i could get help with these issues ive come accross. thanks!

For now I have a tutorial youtube video linked in the readme. Check that out and if you have more questions reply to this issue. Have fun.

**Comment by ytexotic14** [comment]
im using PowerShell Token Grabber btw if you got mistaken

**Comment by KDot227** [comment]
> im using PowerShell Token Grabber btw if you got mistaken

![image](https://github.com/Somali-Devs/Kematian-Stealer/assets/110929758/7d8695e9-b28f-4a30-a19f-7efcfbc55aa5)
https://youtu.be/k-vastcKfwY
